apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: test
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: subedishiva61/reactapp:v1
        ports:
        - containerPort: 80