apiVersion: v1
kind: Service
metadata:
  name: app-svc
  namespace: test
  labels:
    app: app-projects
spec:
  type: NodePort
  selector:
    app: app
  ports:
    - port: 80           # this can be change right here 
      targetPort: 3000   # it has match with program 